### ISSUE TITLE
non-character shortname breaks optparse_from_long

### ISSUE THREAD

**Issue by E5ten** [skeeto/optparse#16]
If someone wants to have a longopt without a corresponding shortopt, it can be simpler to use values above 255 (maximum unsigned char), instead of using longindex. e.g.
```c
struct optparse_long long_options[] = {
    { "opt1", 256, OPTPARSE_NONE },
    { "opt2", 'o', OPTPARSE_NONE }
```
However, in optparse_from_long(), it is only checked that shortname exists, not that it is a valid character, so regardless of validity it is added to the shortopt string, which causes shortopts used after the invalid character (like using -o for the example above) to be considered invalid.
I think the solution here would be to make sure that shortname doesn't just exist, but falls within a valid range (probably below 128).

**Comment by crowja** [comment]
Seems reasonable and practical.

**Comment by skeeto** [comment]
This is a good idea, thanks! I pulled the upper bound down to "< 127" 
since anything above that is ill-defined, and Optparse doesn't support 
multibyte short options (i.e. it's not going to decode UTF-8 to match a 
larger short option).

**Comment by E5ten** [comment]
Thanks, looks good.
