### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by ewd340** [skeeto/optparse#22]
Hello, while writing tests for a program that uses optparse, I stumbled on this segfault situation. I tried to summarize/reproduce it in this little program that crashes as soon as it is executed.

```c
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

#define OPTPARSE_IMPLEMENTATION
#define OPTPARSE_API static
#include "optparse.h"

int fake_main(int argc, char **argv)
{
    struct optparse_long longopts[] = {
        {"amend", 'a', OPTPARSE_NONE},
        {"brief", 'b', OPTPARSE_NONE},
        {"color", 'c', OPTPARSE_REQUIRED},
        {"delay", 'd', OPTPARSE_OPTIONAL},
        {0}
    };

    bool amend = false;
    bool brief = false;
    const char *color = "white";
    int delay = 0;

    char *arg;
    int option;
    struct optparse options;

    optparse_init(&options, argv);
    while ((option = optparse_long(&options, longopts, NULL)) != -1) {
        switch (option) {
        case 'a':
            amend = true;
            break;
        case 'b':
            brief = true;
            break;
        case 'c':
            color = options.optarg;
            break;
        case 'd':
            delay = options.optarg ? atoi(options.optarg) : 1;
            break;
        case '?':
            fprintf(stderr, "%s: %s\n", argv[0], options.errmsg);
            exit(EXIT_FAILURE);
        }
    }

    printf("chosen color %s and delay %d\n", color, delay);

    /* Print remaining arguments. */
    while ((arg = optparse_arg(&options)))
        printf("%s\n", arg);

    return 0;
}

int main(int argc, char *argv[])
{
    fake_main(4, (char *[]){"fakeprg", "--color", "red", "-d", "4"});
    return 0;
}
```
When run, this program segfaults. Using `gdb`, I can track this back to `optparse_is_dashdash(const char *arg)`. I don't actually understand 100% of optparse's code, but I thought that the line:

```c
return arg != 0 && arg[0] == '-' && arg[1] == '-' && arg[2] == '\0';
```

may indeed segfault if `arg` is not that long, or am I just missing or forgetting something with the code above ?

**Comment by N-R-K** [comment]
>     fake_main(4, (char *[]){"fakeprg", "--color", "red", "-d", "4"});

`argv[argc]` needs to be equal to null. Add `NULL` at the end and increase the argc count by one.

**Comment by skeeto** [comment]
It's critical that argv[argc] is a null pointer. That's required by the C 
standard for main(), and Optparse assumes the same. In particular, note 
how it never accepts your argc, so it relies entirely on that null pointer 
to find the end of argv. That's the purpose of the `arg != 0` check.

So in your example, "4" must instead be a null pointer. Alternatively add 
a null pointer to the end of argv, in which case argc would be 5.

**Comment by ewd340** [comment]
Thank you so much @N-R-K and @skeeto !

I was almost certain that I was missing something, and I hesitated before submitting this issue. Sorry for the noise :disappointed:
